### PR TITLE
feat: packaging and add socket

### PR DESCRIPTION
**Pull request by Cruise-z**
The socket program is a simple tool for socket based connections. It can be used to create simple daemons (in both standalone and inetd mode), to connect to other daemons or to redirect ports.

log: packaging and add socket
issue: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/230

### CODE REVIEW

**Comment by Cruise-z** [comment]
@Zeno-sole 构建成功，请老师检查：

**Comment by Cruise-z** [comment]
@UTsweetyfish 老师捞捞这个

**Comment by Cruise-z** [comment]
@hudeng-go 老师看下这个

**Review by chenchongbiao — APPROVED** [review]

**Pull request merged**
